env: ${ENV}

mongoUri: ${MONGO_URI}
mongoDatabase: ${MONGO_DB}

webUrl: ${WEB_URL}

awsRegion: us-east-1

s3BucketData: mono-${ENV}-data
s3BucketMedia: mono-${ENV}-media
sqsWorkQueueName: mono-${ENV}-work
githubClientId: ${GITHUB_CLIENT_ID}
githubClientSecret: ${GITHUB_CLIENT_SECRET}

workerConfig:
  maxThreads: 4

stripeSecretKey: ${STRIPE_SECRET_KEY}
stripeSigningSecret: not_in_use

enableSlack: true
slackUsername: mono
slackChannel: mono
slackIconUrl: https://mono.com/img/mono.png
slackWebhookUrl: ${SLACK_WEBHOOK_URL}

emailService: mailgun
mailgunPrivateKey: ${MAILGUN_PRIVATE_KEY}
mailgunDomain: ${MAILGUN_DOMAIN}

logging:
  level: INFO
  loggers:
    'io.swagger.converter.ModelConverters': ERROR

swagger:
  resourcePackage: com.mono.api.resources
